### ISSUE TITLE
Config option to change SSL validation needed

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm-Exchange/stackstorm-jira#1]
As a user, I would like to have the option to specify `verify: False`, or provide a path to an alternative CA bundle.

This will allow me to use this pack with self-hosted Jira systems that have certificates signed by internal CAs, or self-signed certificates. 

The jira library supports it, so it should just be a pack-level change.

Note that the requests library when used in a Python virtualenv uses its own cacert.pem file, *not* the system CA store. So the usual process, of adding the CA certificate to `/etc/ssl/certs` won't work.

**Comment by punkrokk** [comment]
This is a very common use case. +1
