### ISSUE TITLE
Package Install Failed

### ISSUE THREAD

**Issue by punkrokk** [StackStorm-Exchange/stackstorm-jira#3]
On a clean install of StackStorm. My jira package install is failing. It looks like either a pip or gcc problem. I'll reply back if I figure it out. There's a chance it's a resource problem - but that would be crappy IMHO. It's a t2.small on EC2 (1 CPU and 2GB of RAM)

Full log is in this gist: https://gist.github.com/punkrokk/72f6cf9ecc4c9878cc4a42ecab43907a

Here's what I think is meaningful: 

  creating build/temp.linux-x86_64-2.7/build
  creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
  {standard input}: Assembler messages:
  {standard input}:13999: Warning: end of file not at end of a line; newline inserted
  {standard input}:15955: Error: number of operands mismatch for `lea'
  {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
  gcc: internal compiler error: Killed (program cc1)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <http://bugzilla.redhat.com/bugzilla> for instructions.
  error: command 'gcc' failed with exit status 4
  
  ----------------------------------------
  Running setup.py clean for cryptography
Failed to build cryptography

**Comment by LindsayHill** [comment]
FWIW, Jira pack install succeeds on an ST2 system running on up to date Centos 7, with 2vCPU & 2GB.

**Comment by punkrokk** [comment]
Roger that - I'll try that - any way to solve for this on a t2.small? -  which is what I use for a lot of testing. I'm probably not the only one.

**Comment by LindsayHill** [comment]
Don't know. You'd need to dig into it to see if it is indeed a resource problem. If it is, I don't know what options there to tell pip/gcc to operate with reduced resources

**Comment by punkrokk** [comment]
OK - so I got it working. I had to do two things: 

1. Enable a temporary swap file: 
```
sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo /sbin/mkswap /var/swap.1
sudo chmod 600 /var/swap.1
sudo /sbin/swapon /var/swap.1
```

2. From https://cryptography.io/en/latest/installation/#building-cryptography-on-linux
`sudo yum install gcc libffi-devel python-devel openssl-devel`

FYI I'm using the official Cent OS 7 AMI.

**Comment by LindsayHill** [comment]
Thanks for the update @punkrokk. The dependencies doesn't surprise me, but the memory/swap one is interesting. MongoDB uses a good chunk of memory on a base ST2 system, which might have just been tipping things over the edge. 

Would you mind submitting a PR to the README.md to add those additional requirements?
