### ISSUE TITLE
add_field_value fails

### ISSUE THREAD

**Issue by ytjohn** [StackStorm-Exchange/stackstorm-jira#35]
I just install the jira pack - everything seems to work except the add field. I fixed it locally, but I want to understand if add_field_value and update are separate concepts and if I should instead create an action for update field. 

If I run jira.add_field_value I get back the following response

```
\tresponse text = {\"errorMessages\":[\"Field with id' customfield_10028' and name 'Hostname' does not support operation 'add' Supported operation(s) are: 'set'\"],\"errors\":{}}
```

But if I change [add_field_value.py#L11](https://github.com/StackStorm-Exchange/stackstorm-jira/blob/master/actions/add_field_value.py#L11) to use `issue.update`, that works.

```python
        # issue.add_field_value(field, value)
        issue.update(fields={field: value})
```

**Comment by ytjohn** [comment]
I answered my own question. add_field_value adds a value to a multiple value field without affecting the existing values. To update an existing field, you want to make a separate action, which I did locally and may create a PR for, but it's essentially one yaml and a python script like so:

```
from lib.base import BaseJiraAction

__all__ = [
    'UpdateFieldValue'
]


class AddFieldValue(BaseJiraAction):
    def run(self, issue_key, field, value, notify):
        
        issue = self._client.issue(issue_key)
        issue.update(fields={field: value}, notify=notify)
        result = issue.fields.labels
        return result

```

**Comment by blag** [comment]
I'm glad you were able to get this working! And we would be very interested in your PR.
